### ISSUE TITLE
How to deploy to default module and specific module

### ISSUE THREAD

**Issue by masrodjie** [Venditan/appengine-deploy#6]
Let say i want to deploy the same code to : https://appid.appspot.com and https://mymodule.appspot.com. Is it possible and how to do it?
Thanks

**Comment by tomwalder** [comment]
Yes, you can do this no problem.

You should find the information you need in the README.
https://github.com/Venditan/appengine-deploy

If you have any specific questions, I would be happy to answer

**Comment by tomwalder** [comment]
Closing this thread, feel free to reopen if you need more help!
